services:
    postgres:
      image: postgres
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: admin@123
        POSTGRES_DB: postgres
      volumes:
        - ./raw_data:/input_data
        - ./temp:/temp
        - ./warehouse_setup:/docker-entrypoint-initdb.d
      healthcheck:
        test: ["CMD", "pg_isready", "-U"]
        interval: 5s
        retries: 5
      restart: always
      ports:
        - "5432:5432"