config:
  send_anonymous_usage_stats: False

dbtproject:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 5
      host: localhost
      port: 5432
      user: postgres
      pass: admin@123
      dbname: postgres
      schema: warehouse
